[package]
name = "prng"
version = "0.1.0"
authors = ["Magamedrasul Ibragimov <curryrasul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
clap = "2.33.3"
num-bigint = "0.4"
